# Generated by Django 6.0 on 2026-01-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='force_password_change',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('firma', 'Firma'), ('eczane', 'Eczane')], default='firma', max_length=10),
        ),
    ]
