# Generated by Django 6.0 on 2026-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_force_password_change_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eczane', 'Eczane'), ('firma', 'Firma')], default='firma', max_length=10),
        ),
    ]
