# Generated by Django 6.0 on 2026-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Adresi'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sorumlu Personel'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacist_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eczacı Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_address',
            field=models.TextField(blank=True, null=True, verbose_name='Eczane Adresi'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ruhsat No'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eczane Adı'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No'),
        ),
    ]
