# Generated by Django 6.0 on 2026-02-06 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_company_address_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_apply_discount',
            field=models.BooleanField(default=True, verbose_name='İskonto uygulayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_invoice_revision',
            field=models.BooleanField(default=False, verbose_name='Fatura revize onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_offers',
            field=models.BooleanField(default=False, verbose_name='Teklifleri onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_pharmacy_offers',
            field=models.BooleanField(default=True, verbose_name='Teklif onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_offer',
            field=models.BooleanField(default=True, verbose_name='Teklif oluşturabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_own_offer',
            field=models.BooleanField(default=True, verbose_name='Kendi tekliflerini silebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_own_offer',
            field=models.BooleanField(default=True, verbose_name='Kendi tekliflerini düzenleyebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_enter_invoice',
            field=models.BooleanField(default=True, verbose_name='Fatura bilgisi girebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_reject_pharmacy_offers',
            field=models.BooleanField(default=True, verbose_name='Teklif reddedebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_offer',
            field=models.BooleanField(default=True, verbose_name='Teklif gönderebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_all_offers',
            field=models.BooleanField(default=False, verbose_name='Tüm teklifleri görebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Firma için: Firma Yöneticisi | Eczane için: Eczacı', verbose_name='Yönetici mi?'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Bu personelin bağlı olduğu yönetici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Bağlı Olduğu Yönetici'),
        ),
    ]
