# Generated by Django 6.0 on 2026-02-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_can_apply_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_approve_offers',
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Bu kullanıcıyı kim onayladı?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_activate_deactivate_staff',
            field=models.BooleanField(default=False, verbose_name='Personeli aktif/pasif yapabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_apply_high_discount',
            field=models.BooleanField(default=False, verbose_name='%20+ iskonto uygulayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_high_value_offers',
            field=models.BooleanField(default=False, verbose_name='50K+ teklifleri onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_high_value_pharmacy_offers',
            field=models.BooleanField(default=False, verbose_name='50K+ teklifleri onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_pharmacy_staff',
            field=models.BooleanField(default=False, verbose_name='Personel onaylayabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_all_offers',
            field=models.BooleanField(default=False, verbose_name='Tüm teklifleri silebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_all_offers',
            field=models.BooleanField(default=False, verbose_name='Tüm teklifleri düzenleyebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_invoice',
            field=models.BooleanField(default=False, verbose_name='Fatura düzenleyebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False, verbose_name='Veri dışa aktarabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_invite_staff',
            field=models.BooleanField(default=False, verbose_name='Personel davet edebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_pharmacy_staff',
            field=models.BooleanField(default=False, verbose_name='Personel yönetebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_staff_permissions',
            field=models.BooleanField(default=False, verbose_name='Personel yetkilerini düzenleyebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_promote_to_manager',
            field=models.BooleanField(default=False, verbose_name='Personeli yönetici yapabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_financial_data',
            field=models.BooleanField(default=False, verbose_name='Finansal verileri görebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='Raporları görebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobil Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_responsible_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Yetkili Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_tax_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_expires',
            field=models.DateTimeField(blank=True, help_text='Davetiye linkinin son kullanma tarihi', null=True, verbose_name='Davetiye Geçerlilik'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Personel kaydı için özel token', max_length=100, null=True, unique=True, verbose_name='Davetiye Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Bu personeli kim davet etti?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Davet Eden'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=True, help_text='Pasif kullanıcılar sisteme giremez', verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_email',
            field=models.EmailField(blank=True, help_text='Personel bu email ile kayıt olabilir', max_length=254, null=True, verbose_name='Eczane Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobil Telefon'),
        ),
        migrations.AddField(
            model_name='user',
            name='pharmacy_tax_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Tam Ünvanı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sabit Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkili Kişi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pharmacy_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sabit Telefon'),
        ),
    ]
