# Generated by Django 6.0 on 2026-02-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_can_approve_offers_user_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Adres Başlığı')),
                ('address_type', models.CharField(choices=[('headquarter', 'Merkez'), ('branch', 'Şube'), ('warehouse', 'Depo'), ('other', 'Diğer')], default='branch', max_length=20, verbose_name='Adres Tipi')),
                ('address_line', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Kişisi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
