# Generated by Django 6.0 on 2026-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_products',
            field=models.BooleanField(default=False, verbose_name='Ürün Yönetebilir (Ekle/Düzenle)'),
        ),
    ]
