# Generated by Django 6.0 on 2026-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_can_manage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_revise_offer',
            field=models.BooleanField(default=False, verbose_name='Teklif Revize Edebilir'),
        ),
    ]
