# Generated by Django 6.0 on 2026-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_can_revise_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_update_product_prices',
            field=models.BooleanField(default=False, verbose_name='Ürün Fiyatlarını Güncelleyebilir'),
        ),
    ]
