# Generated by Django 6.0 on 2026-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_can_update_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kvkk_accepted',
            field=models.BooleanField(default=False, verbose_name='KVKK Onayı'),
        ),
        migrations.AddField(
            model_name='user',
            name='kvkk_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KVKK Onay Tarihi'),
        ),
    ]
