# Generated by Django 6.0 on 2026-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Eczaneye Gönderildi')], default='draft', max_length=20),
        ),
    ]
