# Generated by Django 6.0 on 2026-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_offer_sent_at_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Eczaneye Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20),
        ),
    ]
