# Generated by Django 6.0 on 2026-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_offer_approved_at_offer_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Yok'), ('percent', '%'), ('amount', '₺')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
