# Generated by Django 6.0 on 2026-01-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offeritem_discount_type_offeritem_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
