# Generated by Django 6.0 on 2026-01-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offeritem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='original_offer',
            field=models.ForeignKey(blank=True, help_text='Bu teklif bir revize ise, orijinal teklif', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='products.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='revised_at',
            field=models.DateTimeField(blank=True, help_text='Revize edilme tarihi', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='revision_note',
            field=models.TextField(blank=True, help_text='Revize notu', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='revision_number',
            field=models.IntegerField(default=1, help_text='Revizyon numarası'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Eczaneye Gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('revised', 'Revize Edildi')], default='draft', max_length=20),
        ),
    ]
