# Generated by Django 6.0 on 2026-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offer_original_offer_offer_revised_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='overall_discount_type',
            field=models.CharField(choices=[('none', 'Yok'), ('percent', '%'), ('amount', '₺')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='overall_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
