# Generated by Django 6.0 on 2026-02-03 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_offer_overall_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Onaylayan eczane personeli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_deadline',
            field=models.DateField(blank=True, help_text='Termin Tarihi', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Fatura Tarihi', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Fatura No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Reddeden eczane personeli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
