# Generated by Django 6.0 on 2026-02-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offer_approved_by_offer_delivery_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='invoice_revision_approved',
            field=models.BooleanField(default=False, help_text='Yönetici onayladı'),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_revision_pending',
            field=models.BooleanField(default=False, help_text='Revize talebi bekliyor'),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_revision_reason',
            field=models.TextField(blank=True, help_text='Revize nedeni', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='invoice_revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_revision_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
