# Generated by Django 6.0 on 2026-02-06 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_favoritedraft_favoriteproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approved_by_manager',
            field=models.ForeignKey(blank=True, help_text='Onaylayan yönetici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='manager_approval_pending',
            field=models.BooleanField(default=False, help_text='Yönetici onayı bekliyor mu?'),
        ),
        migrations.AddField(
            model_name='offer',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, help_text='Yönetici onay tarihi', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, help_text='Yönetici red nedeni', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='requires_manager_approval',
            field=models.BooleanField(default=False, help_text='Yönetici onayı gerekiyor mu? (≥50K teklifler)'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('offer_created', 'Teklif Oluşturuldu'), ('offer_updated', 'Teklif Güncellendi'), ('offer_deleted', 'Teklif Silindi'), ('offer_sent', 'Teklif Gönderildi'), ('offer_sent_for_approval', 'Teklif Yönetici Onayına Gönderildi'), ('manager_approved_offer', 'Yönetici Teklifi Onayladı'), ('manager_rejected_offer', 'Yönetici Teklifi Reddetti'), ('offer_approved', 'Teklif Onaylandı'), ('offer_rejected', 'Teklif Reddedildi'), ('discount_applied', 'İskonto Uygulandı'), ('discount_approval_requested', 'İskonto Onay Talebi'), ('invoice_created', 'Fatura Oluşturuldu'), ('invoice_updated', 'Fatura Güncellendi'), ('invoice_revision_requested', 'Fatura Revize Talebi'), ('invoice_revision_approved', 'Fatura Revize Onaylandı'), ('invoice_revision_rejected', 'Fatura Revize Reddedildi'), ('offer_revised', 'Teklif Revize Edildi'), ('user_created', 'Kullanıcı Oluşturuldu'), ('user_approved', 'Kullanıcı Onaylandı'), ('user_permissions_changed', 'Kullanıcı Yetkileri Değiştirildi')], help_text='Yapılan işlem', max_length=50)),
                ('description', models.TextField(help_text='İşlem detayı')),
                ('metadata', models.JSONField(blank=True, help_text='Ek bilgiler (JSON formatında)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='İşlemin yapıldığı IP adresi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='İşlem zamanı')),
                ('offer', models.ForeignKey(blank=True, help_text='İlgili teklif (varsa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='products.offer')),
                ('target_user', models.ForeignKey(blank=True, help_text='İşlemin hedef kullanıcısı (varsa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='İşlemi yapan kullanıcı', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivite Logu',
                'verbose_name_plural': 'Aktivite Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='products_ac_created_bbe500_idx'), models.Index(fields=['user', '-created_at'], name='products_ac_user_id_2a93bb_idx'), models.Index(fields=['offer', '-created_at'], name='products_ac_offer_i_cef3ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bildirim başlığı', max_length=255)),
                ('message', models.TextField(help_text='Bildirim mesajı')),
                ('notification_type', models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata')], default='info', help_text='Bildirim tipi', max_length=20)),
                ('link', models.CharField(blank=True, help_text='Yönlendirilecek link', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Okundu mu?')),
                ('read_at', models.DateTimeField(blank=True, help_text='Okunma zamanı', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma zamanı')),
                ('offer', models.ForeignKey(blank=True, help_text='İlgili teklif (varsa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.offer')),
                ('user', models.ForeignKey(help_text='Bildirimin alıcısı', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='products_no_user_id_81bb20_idx')],
            },
        ),
    ]
