# Generated by Django 6.0 on 2026-02-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address'),
        ('products', '0013_offer_approved_by_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_items', to='accounts.address', verbose_name='Teslimat Adresi'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='discount_type',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
