# Generated by Django 6.0 on 2026-02-12 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_offeritem_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 12, 8, 9, 46, 36118, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
