# Generated by Django 6.0 on 2026-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fiyat Güncelleme Tarihi'),
        ),
    ]
