# Generated by Django 6.0 on 2026-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_offer_price_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price_updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='price_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fiyat Güncelleme Tarihi'),
        ),
    ]
